### ISSUE TITLE
Using docker secrets for API key values

### ISSUE THREAD

**Issue by nbn22385** [I-am-PUID-0/pd_zurg#3]
**Is your feature request related to a problem? Please describe.**

I can't figure out how to use a Docker secrets file to handle my RD API key using the provided docker image ([Docs](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose)). Steps I've taken:

1. Populate a file containing my token:
```bash
printf "MY-RD-API-TOKEN" > rd_token.secret
```
2. Add the following to my docker-compose.yml to use the secret:
```yml
secrets: 
  rd_token:
    file: ./rd_token.secret
...
services:
  pd_zurg:
    environment:  
      - RD_API_KEY=/run/secrets/rd_token      # Referencing the secret directly did not work
      - RD_API_KEY_FILE=/run/secrets/rd_token # Appending _FILE did not work
    ...
```

**Describe the solution you'd like**

Support or instructions for handling sensitive tokens via Docker secrets

Thank you!
