### ISSUE TITLE
Implement rar2fs into pd_zurg

### ISSUE THREAD

**Issue by jayshai** [I-am-PUID-0/pd_zurg#30]
**Is your feature request related to a problem? Please describe.**

RAR files are unable to be read by RD and therefore Plex which causes issues for quite a few cached torrents that show up as RAR files regardless if only movie files are selected.

**Describe the solution you'd like**

I've read about rar2fs being a viable solution to this as it can read .rar files and the content within.

**Describe alternatives you've considered**

Don't believe there any many alternatives other than completely ignoring them via zurg config.

**Comment by I-am-PUID-0** [comment]
Changed to Won't Do. Zurg will support RARs.

**Comment by jayshai** [comment]
Thanks, has this already been implemented then as it shows on the roadmap as Done?

**Comment by I-am-PUID-0** [comment]
> Thanks, has this already been implemented then as it shows on the roadmap as Done?

Zurg is adding support for RAR files, but it is only available for the sponsored versions currently:


```yml
# Action to take when encountering RAR files (extract, delete, or none)
rar_action: extract
# Add file extensions that you want to be considered playable (not moved to the unplayable directory)
addl_playable_extensions:
- mp3
- flac
```
