### ISSUE TITLE
Jellyseerr accepts request but pd_zurg doesnt pick that job to cache torrent using real debrid

### ISSUE THREAD

**Issue by pvbhanuteja** [I-am-PUID-0/pd_zurg#34]
**To Reproduce**

Steps to reproduce the behavior.

Below is the compose file to launch

```
version: "3.8"

services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    ## Optionally, specify a specific version of pd_zurg
    # image: iampuid0/pd_zurg:2.0.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /pd_zurg/config:/config
      ## Location for logs
      - /pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - /pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg     
      - /pd_zurg/AD:/zurg/AD   
      ## Location for rclone mount to host
      - /pd_zurg/mnt:/data:shared       
    environment:
      - TZ=America/Los_Angeles
      ## Zurg Required Settings
      - ZURG_ENABLED=true      
      - RD_API_KEY=RD_API_KEY
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=pd_zurg
      ## Plex Debrid Required Settings
      - PD_ENABLED=true
      ## To utilize plex_debrid with Plex, the following environment variables are required
      # - PLEX_USER=pvbhan
      # - PLEX_TOKEN=
      # - PLEX_ADDRESS=http://plex:32400
      - PD_UPDATE=true
      - JF_API_KEY=APIcwecew
      - JF_ADDRESS=http://jellyfin:8096
      - SEERR_API_KEY=seerapi_placeholder
      - SEERR_ADDRESS=http://jellyseerr:5055

    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges


# add jellyfin and Jellyseerr to the docker-compose.yml file
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
     - /dev/dri:/dev/dri   # For GPU transcoding
    volumes:
      - /jellyfin/config:/config
      - /pd_zurg/mnt:/rclone  # Same mount point as used in pd_zurg for the debrid rclone mount
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 8096:8096
    depends_on:  # Used to delay the startup of jellyfin to ensure the rclone mount is available.
      pd_zurg: # set to the name of the container running rclone
        condition: service_healthy

  jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
          - LOG_LEVEL=debug
          - TZ=America/Los_Angeles
      ports:
          - 5055:5055
      volumes:
          - /jellyseerr/config:/app/config
      restart: unless-stopped
      depends_on:  # Used to delay the startup of jellyseerr to ensure the rclone mount is available.
        pd_zurg: # set to the name of the container running rclone
          condition: service_healthy
```

**Screenshots**

jellyseerr logs after adding a movie 

2024-02-10T13:09:00.059Z [debug][Jobs]: Starting scheduled job: Download Sync
2024-02-10T13:10:00.032Z [debug][Jobs]: Starting scheduled job: Download Sync
2024-02-10T13:10:00.055Z [info][Jobs]: Starting scheduled job: Jellyfin Recently Added Sync
2024-02-10T13:10:00.057Z [info][Jellyfin Sync]: Jellyfin Sync Starting {"sessionId":"bc79487b-3be2-44f5-aca2-2c2363410c4a"}
2024-02-10T13:10:00.082Z [info][Jellyfin Sync]: Beginning to process recently added for library: Movies
2024-02-10T13:10:00.201Z [error][Jellyfin Sync]: Failed to process Jellyfin item, id: 1344ecaaaaa667ffad7678fefc47a475 {"errorMessage":"Unable to find TMDb ID","jellyfinitem":{"Name":"Koi... Mil Gaya Hindi (2003) 1080p WEBDL x265 By SagarSingha(TeamDMR) 1st On Net","ServerId":"61c1ef018dee40b384dd161ddf47b7fc","Id":"1344ecaaaaa667ffad7678fefc47a475","Container":"mkv,webm","ChannelId":null,"RunTimeTicks":95276285952,"ProductionYear":2003,"IsFolder":false,"Type":"Movie","UserData":{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"1344ecaa-aaa6-67ff-ad76-78fefc47a475"},"ChildCount":0,"VideoType":"VideoFile","ImageTags":{"Primary":"e3308e230baae51aa68584398d103268"},"BackdropImageTags":[],"ImageBlurHashes":{"Primary":{"e3308e230baae51aa68584398d103268":"WAA,tPX+Imt1TJxucpsqj=tRs:f+01n5%4t8nORP;nS}oNi_Ntn$"}},"LocationType":"FileSystem","MediaType":"Video"}}
2024-02-10T13:10:00.248Z [debug][Jellyfin Sync]: Title already exists and no new media types found Laar
2024-02-10T13:10:00.268Z [debug][Jellyfin Sync]: Title already exists and no new media types found Dune
2024-02-10T13:10:00.291Z [debug][Jellyfin Sync]: Title already exists and no new media types found Bāhubali: The Beginning
2024-02-10T13:10:00.294Z [debug][Jellyfin Sync]: Title already exists and no new media types found Tumbbad
2024-02-10T13:10:00.295Z [debug][Jellyfin Sync]: Title already exists and no new media types found Oppenheimer
2024-02-10T13:10:00.304Z [debug][Jellyfin Sync]: Title already exists and no new media types found RRR
2024-02-10T13:10:00.310Z [debug][Jellyfin Sync]: Title already exists and no new media types found Bāhubali 2: The Conclusion
2024-02-10T13:10:00.329Z [debug][Jellyfin Sync]: Title already exists and no new media types found The Dark Knight
2024-02-10T13:10:00.372Z [debug][Jellyfin Sync]: Title already exists and no new media types found Killers of the Flower Moon
2024-02-10T13:10:00.374Z [debug][Jellyfin Sync]: Title already exists and no new media types found Barbie
2024-02-10T13:10:00.378Z [info][Jellyfin Sync]: Request for The Dark Knight exists. New media types set to AVAILABLE
2024-02-10T13:10:04.381Z [info][Jellyfin Sync]: Recently Added Scan Complete
2024-02-10T13:10:05.117Z [info][Jobs]: Starting scheduled job: Plex Watchlist Sync
2024-02-10T13:11:00.049Z [debug][Jobs]: Starting scheduled job: Download Sync
2024-02-10T13:12:00.061Z [debug][Jobs]: Starting scheduled job: Download Sync
2024-02-10T13:12:12.292Z [debug][API]: Something went wrong retrieving movie ratings {"errorMessage":"[IMDB RADARR PROXY API] Failed to retrieve movie ratings: Cannot read properties of null (reading 'Value')","movieId":"866398"}
2024-02-10T13:12:22.445Z [debug][API]: Something went wrong retrieving movie ratings {"errorMessage":"[IMDB RADARR PROXY API] Failed to retrieve movie ratings: Cannot read properties of null (reading 'Value')","movieId":"866398"}
2024-02-10T13:12:56.217Z [info][Media Request]: No Radarr server configured, skipping request processing {"requestId":2,"mediaId":12}
2024-02-10T13:12:56.230Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_APPROVED {"subject":"Guntur Kaaram (2024)"}

pd_zurg logs after the movie request

           __                  __     __         _     __
    ____  / /__  _  __    ____/ /__  / /_  _____(_)___/ /
   / __ \/ / _ \| |/_/   / __  / _ \/ __ \/ ___/ / __  /
  / /_/ / /  __/>  <    / /_/ /  __/ /_/ / /  / / /_/ /
 / .___/_/\___/_/|_|____\__,_/\___/_.___/_/  /_/\__,_/
/_/               /_____/                         [v2.95]

Options/

1) Run
2) Settings
3) Ignored Media
4) Scraper

Type exit to quit.

Choose an action: Feb 10, 2024 04:34:08 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	Your account will expire in 33 days
Feb 10, 2024 04:34:09 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Fetched info for 31 torrents
Feb 10, 2024 04:34:09 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Compiled into 24 torrents, 0 were missing info
Feb 10, 2024 04:34:09 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Starting periodic repair job
Feb 10, 2024 04:34:09 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Starting periodic refresh job
Feb 10, 2024 04:46:24 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Removing torrent Killers.of.the.Flower.Moon.2023.2160p.WEB-DL.DV.HDR.HEVC-Нечипорук from zurg database (not real-debrid)
Feb 10, 2024 04:46:24 - ERROR - rclone mount name "pd_zurg": movies/Killers.of.the.Flower.Moon.2023.2160p.WEB-DL.DV.HDR.HEVC-Нечипорук/: Dir.Remove failed to remove directory: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:46:24 - ERROR - rclone mount name "pd_zurg": IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:46:30 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Detected changes! Refreshing 30 torrents
Feb 10, 2024 04:46:31 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Fetched info for 30 torrents
Feb 10, 2024 04:46:31 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Compiled into 23 torrents, 0 were missing info
Feb 10, 2024 04:46:31 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Finished refreshing torrents
Feb 10, 2024 04:46:31 - ERROR - Zurg w/ RealDebrid subprocess: 	manager	Failed to execute hook on_library_update: error executing script: exit status 2; stderr: sh: can't open 'plex_update.sh': No such file or directory
Feb 10, 2024 04:47:32 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Removing torrent Interstellar.2014.IMAX.2160p.10bit.HDR.BluRay.6CH.x265.HEVC-PSA from zurg database (not real-debrid)
Feb 10, 2024 04:47:32 - ERROR - rclone mount name "pd_zurg": movies/Interstellar.2014.IMAX.2160p.10bit.HDR.BluRay.6CH.x265.HEVC-PSA/: Dir.Remove failed to remove directory: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:47:32 - ERROR - rclone mount name "pd_zurg": IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:47:38 - ERROR - rclone mount name "pd_zurg": movies/Interstellar.2014.IMAX.2160p.10bit.HDR.BluRay.6CH.x265.HEVC-PSA/: Dir.Remove failed to remove directory: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:47:38 - ERROR - rclone mount name "pd_zurg": IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:47:40 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Detected changes! Refreshing 29 torrents
Feb 10, 2024 04:47:41 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Fetched info for 29 torrents
Feb 10, 2024 04:47:41 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Compiled into 22 torrents, 0 were missing info
Feb 10, 2024 04:47:41 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Finished refreshing torrents
Feb 10, 2024 04:47:41 - ERROR - Zurg w/ RealDebrid subprocess: 	manager	Failed to execute hook on_library_update: error executing script: exit status 2; stderr: sh: can't open 'plex_update.sh': No such file or directory
Feb 10, 2024 04:48:37 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Removing torrent Interstellar (2014) (2014) [1080p] from zurg database (not real-debrid)
Feb 10, 2024 04:48:37 - ERROR - rclone mount name "pd_zurg": movies/Interstellar (2014) (2014) [1080p]/: Dir.Remove failed to remove directory: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:48:37 - ERROR - rclone mount name "pd_zurg": IO error: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented
Feb 10, 2024 04:48:40 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Detected changes! Refreshing 28 torrents
Feb 10, 2024 04:48:40 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Fetched info for 28 torrents
Feb 10, 2024 04:48:40 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Compiled into 21 torrents, 0 were missing info
Feb 10, 2024 04:48:40 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Finished refreshing torrents
Feb 10, 2024 04:48:40 - ERROR - Zurg w/ RealDebrid subprocess: 	manager	Failed to execute hook on_library_update: error executing script: exit status 2; stderr: sh: can't open 'plex_update.sh': No such file or directory

**Please complete the following information:**

centos arm64
