### ISSUE TITLE
Cannot delete file from Real debrid

### ISSUE THREAD

**Issue by GSKang94** [I-am-PUID-0/pd_zurg#55]
Hi when I try to remove a movie from plex, I get this message
`Zurg w/ RealDebrid subprocess: 	manager	Removing torrent Wildlife (2018) [WEBRip] [1080p] [YTS.AM] from zurg database (not real-debrid)`

`rclone mount name "pd_zurg": movies/Wildlife (2018) [WEBRip] [1080p] [YTS.AM]/: Dir.Remove failed to remove directory: couldn't list files: Not Implemented Method: NotImplemented: 501 Not Implemented`

so files are only getting deleted locally

This is my `docker-compose` file

```yml
version: "3.8"
services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    stdin_open: true 
    tty: true  
    volumes:
      - /home/pd_zurg/config:/config
      - /home/pd_zurg/log:/log
      - /home/pd_zurg/cache:/cache
      - /home/pd_zurg/RD:/zurg/RD
      - /home/pd_zurg/mnt:/data:shared
    environment:
      - TZ=xxx
      - ZURG_ENABLED=true
      - RD_API_KEY=my-key
      - PLEX_REFRESH=true
      - PLEX_MOUNT_DIR=/rclone/pd_zurg
      - RCLONE_MOUNT_NAME=pd_zurg
      - PD_ENABLED=true
      - DUPLICATE_CLEANUP=true
      - CLEANUP_INTERVAL=1
      - SEERR_API_KEY=my-key
      - SEERR_ADDRESS=http://raspberrypi.local:5055
      - PLEX_USER=Mango.boi
      - PLEX_TOKEN=my-token
      - PLEX_ADDRESS=raspberrypi.local:32400
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
networks: {}

```
