### ISSUE TITLE
WARNING - Rate limit exceeded. Retrying after 1371.8090605735779 seconds

### ISSUE THREAD

**Issue by jopsis** [I-am-PUID-0/pd_zurg#75]
**Describe the bug**

When pd_zurg start shows this errors and not works

```
Oct 18, 2024 16:15:18 - WARNING - Rate limit exceeded. Retrying after 1371.8090605735779 seconds.
Oct 18, 2024 16:15:28 - ERROR - The Zurg RD process is not running.
```

**To Reproduce**

docker-compose.yml

```
version: "3.8"
services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    ## Optionally, specify a specific version of pd_zurg
    # image: iampuid0/pd_zurg:2.0.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: host 
    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup.
      - /storage/docker/containers/pd_zurg/config:/config
      ## Location for logs
      - /storage/docker/containers/pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - /storage/docker/containers/pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /storage/docker/containers/pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg
      #- /pd_zurg/AD:/zurg/AD
      ## Location for rclone mount to host
      - /storage/docker/containers/pd_zurg/mnt:/data:shared
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
      ## Zurg Required Settings
      - ZURG_ENABLED=true
      - RD_API_KEY=BLABLABLA
      ## Zurg Optional Settings
      - ZURG_LOG_LEVEL=DEBUG
     # - ZURG_VERSION=v0.9.2-hotfix.4
      - ZURG_UPDATE=false
      - PLEX_REFRESH=true
      - PLEX_MOUNT_DIR=/storage/docker/containers/pd_zurg/mnt/pd_zurg
     # - ZURG_USER=
     # - ZURG_PASS=
     # - ZURG_PORT=8800
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=pd_zurg
      ## Rclone Optional Settings - See rclone docs for full list
     # - NFS_ENABLED=true
     # - NFS_PORT=8000
     # - RCLONE_LOG_LEVEL=DEBUG
      - RCLONE_CACHE_DIR=/cache
      - RCLONE_DIR_CACHE_TIME=10s
      - RCLONE_VFS_CACHE_MODE=full
      - RCLONE_VFS_CACHE_MAX_SIZE=32G
     # - RCLONE_ATTR_TIMEOUT=8700h
      - RCLONE_BUFFER_SIZE=64M
      - RCLONE_VFS_CACHE_MAX_AGE=4h
      - RCLONE_VFS_READ_CHUNK_SIZE=128M
      - RCLONE_VFS_WRITE_BACK=10s
     # - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=1G
      - RCLONE_ATTR_TIMEOUT=5s
      - RCLONE_TRANSFERS=8
      ## Plex Debrid Required Settings
      - PD_ENABLED=true
      ## To utilize plex_debrid with Plex, the following environment variables are required
      - PLEX_USER=MYUSER
      - PLEX_TOKEN=BLABLALBA
      - PLEX_ADDRESS=http://MYIP:32400
      ## To utilize plex_debrid with Jellyfin, the following environment variables are required - Note that plex_debrid will require addtional setup befor use with Jellyfin
     # - JF_ADDRESS
     # - JF_API_KEY
      ## Plex Debrid Optional Settings
      - PD_UPDATE=true
     # - SHOW_MENU=false
      - SEERR_API_KEY=BLABLABLA
      - SEERR_ADDRESS=http://MYIP:5055
      ## Special Features
     # - AUTO_UPDATE_INTERVAL=12
     # - DUPLICATE_CLEANUP=true
     # - CLEANUP_INTERVAL=1
     # - PDZURG_LOG_LEVEL=DEBUG
     # - PDZURG_LOG_COUNT=2
    # Example to attach to gluetun vpn container if realdebrid blocks IP address
    # network_mode: container:gluetun
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
  ```

**Screenshots**

![image](https://github.com/user-attachments/assets/ed4ecc7a-0573-4660-a0bc-3318d51a86a2)

**Please complete the following information:**
 - OS: LibreELEC
 - Version: LibreELEC (official): 12.0.1 (Generic.x86_64)
 - Supporting Applications: docker and portainer for stacks (docker compose)

**Additional context**

With rclone container I can mount RealDebrid (webdav config)
