### ISSUE TITLE
Premiumize Working, but not Adding Files to /shows or /movies

### ISSUE THREAD

**Issue by camsterguy** [I-am-PUID-0/pd_zurg#83]
Due to the recent RD shutdown, I purchased Premiumize. I removed RD and added Premiumize using my API, as well as Jackett for extra sources.

pd_zurg appears to be processing the requests correctly, as when I add a movie to my watchlist on Plex, I see the request get processed in docker, and when I log into Premiumize I see the movie get downloaded.

However, there appears to be an issue with it being added to the rclone /docker/pd_zurg/mnt/rd/movies as it's not showing up in there or appearing on my Plex library.

I set up my server initially using this guide:
https://docs.google.com/document/d/1wGzoV11vG2jiSiKm_EoShrcig70pWYPDYiYbAXT5jRQ/edit?tab=t.0#heading=h.nu4h35dxqc4q

Is there anything need to get my Premiumize to work with pd_zurg? Thank you for all the help!

Here is my compose:

```
 ## Optionally, specify a specific version of pd_zurg
   version: "3.8"

services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    network_mode: host
    # image: iampuid0/pd_zurg:2.0.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /docker/pd_zurg/config:/config
      ## Location for logs
      - /docker/pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - /docker/pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /docker/pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg     
      - /docker/pd_zurg/AD:/zurg/AD
      ## Location for rclone mount to host
      - /docker/pd_zurg/mnt:/data:shared
    environment:
      - TZ=
      ## Zurg Required Settings
      - ZURG_ENABLED=true
      - RD_API_KEY=FP4V5FWW64CSWXSSRFCBWATRUSVLWKLEUSZ36SWYG6BYA2GH452A
      ## Zurg Optional Settings
     # - ZURG_LOG_LEVEL=DEBUG
     # - ZURG_VERSION=v0.9.2-hotfix.4
      - ZURG_UPDATE=true
      - PLEX_REFRESH=true
      - PLEX_MOUNT_DIR=/docker/pd_zurg/mnt/rd
     # - ZURG_USER=
     # - ZURG_PASS=
      - ZURG_PORT=9999
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=rd
      ## Rclone Optional Settings - See rclone docs for full list
     # - NFS_ENABLED=true
     # - NFS_PORT=8000
     # - RCLONE_LOG_LEVEL=DEBUG
     # - RCLONE_CACHE_DIR=/cache
     # - RCLONE_DIR_CACHE_TIME=10s
     # - RCLONE_VFS_CACHE_MODE=full
     # - RCLONE_VFS_CACHE_MAX_SIZE=100G
     # - RCLONE_ATTR_TIMEOUT=8700h
     # - RCLONE_BUFFER_SIZE=32M
     # - RCLONE_VFS_CACHE_MAX_AGE=4h
     # - RCLONE_VFS_READ_CHUNK_SIZE=32M
     # - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=1G
     # - RCLONE_TRANSFERS=8
      ## Plex Debrid Required Settings
      - PD_ENABLED=true
      ## To utilize plex_debrid with Plex, the following environment variables are required
      - PLEX_USER=cameronvahe
      - PLEX_TOKEN=itskN2xZwLWRFfN49tzg
      - PLEX_ADDRESS=http://localhost:32400
      ## To utilize plex_debrid with Jellyfin, the following environment variables are required - Note that plex_debrid will require addtional setup befor use with Jellyfin
     # - JF_ADDRESS
     # - JF_API_KEY
      ## Plex Debrid Optional Settings
      - PD_UPDATE=true
     # - SHOW_MENU=false
      - SEERR_API_KEY=MTczMjI4ODcxNzEzNzY5OTNlYzU2LTJiZWMtNGU3Ny04MmRmLTg5ODRmNWQyODBkYg==
      - SEERR_ADDRESS=http://localhost:5055
      ## Special Features
     # - AUTO_UPDATE_INTERVAL=12
     # - DUPLICATE_CLEANUP=true
     # - CLEANUP_INTERVAL=1
     # - PDZURG_LOG_LEVEL=DEBUG
     # - PDZURG_LOG_COUNT=2
    # Example to attach to gluetun vpn container if realdebrid blocks IP address 
    # network_mode: container:gluetun  
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
```
